# app.py

# pyrefly: ignore [missing-import]
import streamlit as st
import sys
import os

# Make all local modules importable from the project root
sys.path.append(os.path.dirname(__file__))

# ─ Page config
st.set_page_config(
    page_title="LLM Financial Auditor",
    page_icon="🔍",
    layout="wide"
)

# Load .env locally if python-dotenv is installed (not needed on Streamlit Cloud)
try:
    # pyrefly: ignore [missing-import]
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # On Streamlit Cloud, secrets are already set as environment variables

from extraction.parse_html import extract_sections_from_html
from extraction.extract_metrics import extract_metrics_from_text
from anomaly_detection.rules import detect_anomalies
from llm_module.explainer import explain_anomaly, answer_document_question


# ─ Sidebar
with st.sidebar:
    st.title("🔍 LLM Financial Auditor")
    st.markdown("---")
    st.markdown(
        """
        **What this app does:**
        1. Parses an HTML 10-K financial filing
        2. Extracts key financial metrics via regex
        3. Flags anomalies using rule-based logic
        4. Explains each anomaly using a local LLM (Mistral via Ollama)
        """
    )
    st.markdown("---")
    st.markdown("**Tech Stack**")
    st.code("Python · BeautifulSoup · Regex · Ollama · Streamlit", language=None)
    st.markdown("---")
    st.markdown(
        "Built by [Victor Agbadan](https://github.com/vickCoder7)",
        unsafe_allow_html=True
    )

# ─ Main Page Header
st.title("🏦 LLM-Powered Financial Auditor")
st.markdown(
    "Upload an HTML 10-K financial report to automatically detect anomalies "
    "and generate AI-powered audit explanations."
)
st.markdown("---")

# ─ File Upload
uploaded_file = st.file_uploader(
    "Upload a 10-K HTML Report",
    type=["html", "htm"],
    help="Upload a 10-K SEC filing in HTML format. You can download these from SEC EDGAR."
)

if uploaded_file is None:
    st.info("👆 Upload an HTML 10-K report above to get started.")
    st.stop()   # Stop execution here until a file is provided

# ─ 1. Parse HTML
with st.spinner("Parsing HTML document..."):
    html_content = uploaded_file.read().decode("utf-8", errors="ignore")
    sections = extract_sections_from_html(html_content)

if not sections:
    st.error(
        "❌ No sections found in this file. Make sure it is a valid 10-K HTML report "
        "with 'Item X.' section headers."
    )
    st.stop()

st.success(f"✅ Successfully parsed **{len(sections)} sections** from the report.")

# Reconstruct clean full text of the entire document for Q&A context
full_doc_context = "\n\n".join([f"{title}\n{text}" for title, text in sections.items()])

# ─ 2. Extract Metrics
st.markdown("### 📊 Extracted Financial Metrics")

# Item 7 (MD&A) and Item 8 (Financial Statements) contain the numbers
combined_text = ""
for title, text in sections.items():
    if title.lower().startswith("item 7") or title.lower().startswith("item 8"):
        combined_text += text + "\n"

metrics = extract_metrics_from_text(combined_text)

if not metrics:
    st.warning(
        "⚠️ No financial metrics were extracted. The regex patterns may not match "
        "this document's format. Try a standard SEC 10-K filing."
    )
else:
    # Display metrics as cards in a responsive grid
    cols = st.columns(3)
    metric_items = list(metrics.items())
    for i, (name, value) in enumerate(metric_items):
        with cols[i % 3]:
            st.metric(label=name, value=f"${value:,.0f}M")


# ─ 3. Detect Anomalies
st.markdown("---")
st.markdown("### 🚨 Anomaly Detection Results")

anomalies = detect_anomalies(metrics)

if not anomalies:
    st.success("✅ No anomalies detected. All financial metrics are within normal ranges.")
else:
    st.warning(f"**{len(anomalies)} anomaly(ies) detected.** Review the findings below.")

    # Map severity to Streamlit alert type
    severity_map = {
        "critical": st.error,
        "high": st.error,
        "medium": st.warning,
        "low": st.info
    }

    for anomaly in anomalies:
        severity = anomaly.get("severity", "low")
        alert_fn = severity_map.get(severity, st.info)
        alert_fn(
            f"**[{severity.upper()}]** `{anomaly['metric']}` — {anomaly['reason']}"
        )

# ─ 4. LLM Explanations
if anomalies:
    st.markdown("---")
    st.markdown("### 🤖 AI-Generated Audit Explanations")
    st.markdown(
        "The following explanations are generated by **Groq Llama 3.3 70B**"
    )

    # Cache the LLM call so it doesn't re-run on every page interaction
    @st.cache_data(show_spinner=False)
    def get_explanation(metric_name, section_text, anomaly_reason):
        return explain_anomaly(metric_name, section_text, anomaly_reason)

    for anomaly in anomalies:
        metric_name = anomaly["metric"]
        reason = anomaly["reason"]

        with st.expander(f"📋 Explanation: {metric_name}", expanded=True):
            with st.spinner(f"Generating explanation for '{metric_name}'..."):
                try:
                    explanation = get_explanation(metric_name, combined_text[:2000], reason)
                    st.markdown(explanation)
                except RuntimeError as e:
                    st.error(
                        f"❌ LLM request failed. Is Ollama running?\n\n"
                        f"Run `ollama run mistral` in a separate terminal.\n\n"
                        f"Error: {e}"
                    )

# ─ 5. Interactive Chat
st.markdown("---")
st.markdown("### 💬 Interactive Document Auditor")
st.markdown(
    "Ask questions about this 10-K report (e.g., *'What are the primary risk factors?'*, "
    "*'Summarize the revenue trends'*, or *'Describe the company's liabilities'*)."
)

# Manage state for current file to clear history if a new file is uploaded
if "uploaded_filename" not in st.session_state:
    st.session_state.uploaded_filename = None

if uploaded_file.name != st.session_state.uploaded_filename:
    st.session_state.chat_history = []
    st.session_state.uploaded_filename = uploaded_file.name

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

# Display prior chat messages
for message in st.session_state.chat_history:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# User prompt input
if user_query := st.chat_input("Ask a question about the document..."):
    # Render user query
    with st.chat_message("user"):
        st.markdown(user_query)
    st.session_state.chat_history.append({"role": "user", "content": user_query})

    # Prepare context based on current LLM mode context length limits
    mode = os.getenv("LLM_MODE", "local")
    limit = 25000 if mode == "cloud" else 8000
    context_text = full_doc_context[:limit]

    # Render agent response
    with st.chat_message("assistant"):
        with st.spinner("Analyzing document content..."):
            try:
                response = answer_document_question(
                    query=user_query,
                    context=context_text,
                    history=st.session_state.chat_history[:-1]
                )
                st.markdown(response)
                st.session_state.chat_history.append({"role": "assistant", "content": response})
            except Exception as e:
                st.error(f"❌ Error communicating with the LLM: {e}")

# ─ Raw Data
st.markdown("---")
with st.expander("🗂️ View Raw Parsed Sections"):
    for title, text in sections.items():
        st.markdown(f"**{title}**")
        st.text(text[:500] + ("..." if len(text) > 500 else ""))
        st.markdown("---")


# ─ Download Report
if anomalies:
    st.markdown("---")

    # Build a plain-text report
    report_lines = ["LLM FINANCIAL AUDIT REPORT", "=" * 40, ""]
    report_lines.append(f"File: {uploaded_file.name}")
    report_lines.append(f"Sections Parsed: {len(sections)}")
    report_lines.append("")
    report_lines.append("EXTRACTED METRICS:")
    for name, value in metrics.items():
        report_lines.append(f"  {name}: ${value:,.0f}M")
    report_lines.append("")
    report_lines.append("DETECTED ANOMALIES:")
    for a in anomalies:
        report_lines.append(f"  [{a['severity'].upper()}] {a['metric']}: {a['reason']}")

    report_text = "\n".join(report_lines)

    st.download_button(
        label="⬇️ Download Audit Report (.txt)",
        data=report_text,
        file_name="audit_report.txt",
        mime="text/plain"
    )
